In [1]:
import numpy as np

In [2]:
from numpy import array # import the array constructor itself
a = array([1,2,3]) # now you can call array() without np.
print(a) # [123]

[1 2 3]


In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
#OUTPUT: [12345]
#This is a 1D array with five numbers.

[1 2 3 4 5]


In [4]:
#Add a Number to All Elements
print(a+2)
#OUTPUT:[3 4 5 6 7]
#NumPy automatically adds 2 to every element in the array.

[3 4 5 6 7]


In [5]:
#Multiply All Elements
print(a*3)
#OUTPUT:[3 6 9...]
#Multiplies each number in the array by 3.

[ 3  6  9 12 15]


In [6]:
#4. Check Array Information
print(a.shape)  #Shape of the array
print(a.ndim)   #Number of dimensions
print(a.dtype)  #Data type

(5,)
1
int32


In [1]:
import numpy as np
a=np.arange(4) #This creates: [0, 1, 2, 3]
print(a+4) #Adds 4 to each item

[4 5 6 7]


In [2]:
a=np.array ([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()
print(a.sum())

15.0


In [5]:
#Examples 3- Math between two arrays:
b=np.array([10,20,30,40,50])
print(a+b)

[13.3 24.5 31.2 45.7 50.3]


In [6]:
a.min()
print(a.min())

0.3


In [7]:
# Create an array with 5 decimal numbers
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

In [8]:
# Perform some basic aggregate operations:
print("Sum:", a.sum())       # Adds all numbers → 15.0
print("Minimum:", a.min())   # Smallest number → 0.3
print("Maximum:", a.max())   # Largest number → 5.7
print("Mean:", a.mean())     # Average → 3.0
print("Standard Deviation:", a.std())  # Spread → ~2.01

#a.sum() – adds all numbers in the array.
#a.min() – finds the smallest number.
#a.max() – finds the largest numb


Sum: 15.0
Minimum: 0.3
Maximum: 5.7
Mean: 3.0
Standard Deviation: 2.0079840636817816


In [9]:
#Think of a NumPy array like a row of boxes, each holding a number. Each box has a position number (index) starting from 0.
#For example:
import numpy as np
a = np.array([10, 11, 12, 13, 14, 15])

In [10]:
#INDEXING — Picking a Specific Box
#Just like choosing one box from the shelf.
#Example:
a[4]  # Picks the value at position 4
#Negative Indexing:
#You can also count from the end using negative numbers.
a[-1]  # Last item
# Output: 15


15

In [11]:
a[-6]  # First item
# Output: 10
#Picking Multiple Boxes:
#Use square brackets and list of indexes.
a[[1, 3, 4]]
# Output: array([11, 13, 14])


array([11, 13, 14])

In [12]:
#SLICING — Cutting Out a Section
#Slicing is like cutting a slice of bread  from a loaf.
#Example:
a[1:5]  # From index 1 to 4 (5 is not included)
# Output: array([11, 12, 13, 14])



array([11, 12, 13, 14])

In [13]:
#ITERATING — Going Through Every Item
#Iterating means checking each item one by one, like checking each student's name in a list.
#Example:
for i in a:
    print(i)

10
11
12
13
14
15


In [14]:
#Slice from index 1 up to-but not including-index 5
slice1=a[1:5] 
print("a[1:5]:", slice1)

a[1:5]: [11 12 13 14]


In [18]:
#Same slice but step by 2(every second element)
slice2=a[1:5:2]
print("a[1:5:2]:",slice2)

a[1:5:2]: [11 13]
